version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install time

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
  build:
    commands:
      # Remove git folder
      - rm -rf node_modules
      - rm -rf .git
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codebuild-artifacts-110187550482 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
