version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - printenv
      - chmod +x ./code-build-extras.sh
      - ./code-build-extras.sh

      - THE_GIT_BRANCH=`git symbolic-ref HEAD --short 2>/dev/null`
      - echo "==> THE_GIT_BRANCH = $THE_GIT_BRANCH"
      - echo $THE_GIT_BRANCH
      - echo "-------------------------------"
      - |
        if [ "$CODEBUILD_GIT_BRANCH" == "" ] ; then
          echo "ENTERING THIS LINE HEREEEEEEE"
          CODEBUILD_GIT_BRANCH=`git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'`
          export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/}
        fi

      - echo "==> CODEBUILD = $CODEBUILD_GIT_BRANCH"
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  #pre_build:
    #commands:
      # Discover and run unit tests in the 'tests' directory
      #- npm test
  build:
    commands:
      # Remove git folder
      - rm -rf node_modules
      - rm -rf .git
      - npm install --production
      - aws cloudformation package --template-file $InSamFileName --s3-bucket $S3Bucket --s3-prefix $S3Prefix --output-template-file $OutSamFileName
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - $OutSamFileName
