version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install --production

      # Make sure we have GIT information as env variables
      #- printenv
      - chmod +x ./code-build-extras.sh
      - ./code-build-extras.sh

      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade awscli
  #pre_build:
    #commands:
      # Discover and run unit tests in the 'tests' directory
      #- npm test
  build:
    commands:
      # Remove git folder
      #- rm -rf node_modules
      - rm -rf .git
      #- npm install --production
      - aws cloudformation package --template-file $SAM_TEMPLATE_IN --s3-bucket $S3_BUCKET --s3-prefix $CBUILD_NAME --output-template-file $SAM_TEMPLATE_OUT
artifacts:
  type: zip
  files:
    - $SAM_TEMPLATE_IN
    - $SAM_TEMPLATE_OUT
