AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Parameters:
  EnvName:
    Description: The environment name
    Type: String
Conditions:
  UseCanary: !Equals [!Ref EnvName, prod]
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      AutoPublishAlias: live
      DeploymentPreference:
        Type: !If [UseCanary, Canary10Percent5Minutes, AllAtOnce]
      Environment:
        Variables:
          THE_ENV_NAME: !Ref EnvName
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /time
            Method: GET
  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./second
      AutoPublishAlias: live
      DeploymentPreference:
        Type: !If [UseCanary, Canary10Percent5Minutes, AllAtOnce]
      Environment:
        Variables:
          THE_ENV_NAME: !Ref EnvName
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /greeting
            Method: GET