AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Parameters:
  EnvName:
    Description: The environment name
    Type: String
Conditions:
  UseCanary: !Equals [!Ref EnvName, prod]

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    MemorySize: 128
    Handler: index.handler
    AutoPublishAlias: live
    DeploymentPreference:
      Type: !If [UseCanary, Canary10Percent5Minutes, AllAtOnce]
    Environment:
      Variables:
        ENV: !Ref EnvName

Resources:


  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Events:
        Api:
          Type: Api
          Properties:
            Path: /time
            Method: GET

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./second
      Events:
        Api:
          Type: Api
          Properties:
            Path: /greeting
            Method: GET